### ISSUE TITLE
Select: search visual issues

### ISSUE THREAD

**Issue by edimitchel** [orion-ui/orion-ui#5]
By curiosity, I found several issues on Select component :

- Searchable Select shows a weird search label when the field is focused (background black line). Also, the search submit icon is not well placed.
![image](https://user-images.githubusercontent.com/2922851/230038333-a21143cb-c741-4182-a3a3-bda9747e57bb.png)

- On mobile, Autocomplete Select is hidding the search field as it shows the overlay select items container 
![image](https://user-images.githubusercontent.com/2922851/230038825-f8800252-43b3-4a86-8033-8a7cd02c87cc.png)

**Context:**
Browser: Edge
OS: Windows 10

**Comment by jbmaisner** [comment]
Thanks for your feedback, we'll address this issue in the next hotfix 🤓
