### ISSUE TITLE
OrionSelect : bug on mobile device

### ISSUE THREAD

**Issue by julie-seebauer** [orion-ui/orion-ui#8]
When there is no option available in the OrionSelect component, it is not possible to leave the focus

<img width="413" alt="CleanShot 2023-09-21 at 09 47 32@2x" src="https://github.com/orion-ui/orion-ui/assets/127832278/eaaca044-61d0-4946-a4f1-c7e516aac01b">

**Comment by jbmaisner** [comment]
Fixed in bfd9390c10708ef36b0150ce3692256e3fc5cf6f
