### ISSUE TITLE
[Select] Add fetchClear event

### ISSUE THREAD

**Issue by gbarbaras** [orion-ui/orion-ui#9]
Bonjour Monsieur,

Lors de la customization de la recherche dans un select, je me suis apperçu que la recherche ne fonctionne pas lorsqu'on "clear" la recherche.

Est-il possible d'ajouter un event fetchClear ou un autre mécanisme permettant d'avoir l'information lorsque la recherche est vidée ?

Sincères saluations,

Vive Jue VS !

Cordialement,
Un ancien développeur Angular

**Comment by jbmaisner** [comment]
Dorénavant la recherche se lancera également si le champ est vide. 
Ce comportement peut-être modifié dans la méthode utilisée pour la props `:custom-fetch`.

Un nouvel évènement `@fetch-search-clear` est également émit lorsque le champ de recherche est vidé.

Exemple :

```vue
<template>
  <o-select
    ...
    :custom-fetch="customFetch"
    @fetch-search-clear="cb">
</template>

<script>
async function customFetch (term?: string) {
  console.log(`customFetch term:`, term);
  const resp = await fetch(`https://jsonplaceholder.typicode.com/users`);
  return await resp.json();
}

function cb (e:any) {
  console.log(`🚀 ~ cb ~ e`, e);
}
</script>
```
